name:                 ci-cd-engine
version:              0.1.0.0
visibility:           public
id:                   ci-cd-engine-0.1.0.0-inplace
key:                  ci-cd-engine-0.1.0.0-inplace
license:              MIT
synopsis:
    Research-grade distributed CI/CD engine with Jenkins-style dashboard

abi:                  inplace
exposed:              True
exposed-modules:      Database Docker Server Types UI
import-dirs:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\build"

library-dirs:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

data-dir:             "C:\\Vs\\Haskell\\CI-CD Engine\\."
hs-libraries:         HSci-cd-engine-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:
    aeson-2.2.3.0-fef832b9030f3ab71823c04d915fad13c343a19d
    async-2.2.6-832c197537a7facdff7bee5207aa8b0e2316e6df base-4.18.3.0
    bytestring-0.11.5.4 containers-0.6.7
    http-client-0.7.19-f4eec8bb4be19973b7363abe058bf543711c5a3e
    http-conduit-2.3.9.1-a0cd701f401e932af1af9c27a970d1bb7890aecd
    http-types-0.12.4-794b554c070827cbd079305689037ab4359209e5
    lucid-2.11.20_-fda43d4aa03576dd6e9df8453a5f927b6b633d5d
    monad-logger-0.3.42-af9e2773bb099d73c460da465c5f5af69a380cee
    mtl-2.3.1
    persistent-2.18.1.0-66229f365db07f7b0c747348582ccfe9f3f8a519
    persistent-po_-2.14.3.0-0559a9271cfb462fe795d0058e7f221be6cf2fff
    servant-0.20.3.0-fa530f728f8927565311f0799f22f9b9c3a03c6e
    servant-lucid-0.9.0.6-9837f0792ba18df2d26d5b715a1a9b97ee14b04b
    servant-server-0.20.3.0-d5e6afe528ca0eb86762e8ff747bc8dc455c2831
    stm-2.5.1.0 text-2.0.2 time-1.12.2
    wai-3.2.4-a51729c340450189e720a7dab725f86bf1b35d43
    websockets-0.13.0.0-38918080b622b2cdf2ac9d54f6addec76349ffbe
    yaml-0.11.11_-adeb0482488658d4841e98fb4a591b73fcb4be9f

haddock-interfaces:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\doc\\html\\ci-cd-engine\\ci-cd-engine.haddock"

haddock-html:
    "C:\\Vs\\Haskell\\CI-CD Engine\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\ci-cd-engine-0.1.0.0\\doc\\html\\ci-cd-engine"
